services:
  backup-postgress:
    build: .
    container_name: backup-postgress
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDB: ${PGDB}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
    volumes:
      - ./dump:/dump
